version: '3.8'

services:
  # Servicio de la base de datos MySQL
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  # Servicio de la aplicación web Flask
  webapp:
    build: .
    container_name: webapp_flask
    restart: unless-stopped
    depends_on:
      - db
    expose:
      - "5000"
    volumes:
      - ./webapp:/app/webapp

  # Servicio del proxy inverso Nginx
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: unless-stopped
    ports:
      - "9080:80"
      - "9443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - webapp

# Volumen para persistir los datos de la base de datos
volumes:
  db_data:
